on:
  workflow_dispatch:
  push:
    paths:
      - "gpt-neox-determined/**"
      - ".github/workflows/gpt-neox-determined.yml"
      - ".github/workflows/build.yml"


jobs:
  build:
    uses: ./.github/workflows/build.yml
    with: 
      image-name: gpt-neox-determined
      folder: gpt-neox-determined
      build-args: ""