on:
  workflow_dispatch:
  push:
    paths:
      - "sd-finetuner/**"
      - ".github/workflows/sd-finetuner.yml"
      - ".github/workflows/build.yml"


jobs:
  build:
    uses: ./.github/workflows/build.yml
    with: 
      image-name: sd-finetuner
      folder: sd-finetuner
      build-args: ""