on:
  workflow_dispatch:
  push:
    paths:
      - "slurm-login/**"
      - ".github/workflows/slurm-login.yml"
      - ".github/workflows/build.yml"

jobs:
  build:
    strategy:
      matrix:
        image:
        - name: "slurm-login"
          folder: slurm-login
          build-args: |
            BASE_IMAGE=registry.gitlab.com/coreweave/sunk/dev/controller:2022-11-10_00-37-11.54_EST

    uses: ./.github/workflows/build.yml
    with: 
      image-name: ${{ matrix.image.name }}
      folder: ${{ matrix.image.folder }}
      build-args: ${{ matrix.image.build-args }}
