on:
  workflow_dispatch:
  push:
    paths:
      - "torch-nccl/**"
      - ".github/workflows/torch-nccl.yml"
      - ".github/workflows/build.yml"


jobs:
  build:
    uses: ./.github/workflows/build.yml
    with: 
      image-name: torch-nccl
      folder: torch-nccl
      build-args: ""