on:
  workflow_dispatch:
  push:
    paths:
      - "torch/**"
      - ".github/workflows/torch-nccl.yml"
      - ".github/workflows/torch.yml"
      - ".github/workflows/build.yml"


jobs:
  build:
    strategy:
      matrix:
        image:
          - cuda: 12.0.1
            nccl: 2.17.1-1
            nccl-tests-hash: 5efeee0
          - cuda: 11.8.0
            nccl: 2.16.2-1
            nccl-tests-hash: 5efeee0
        include:
          - torch: 2.0.0
            vision: 0.15.1

    uses: ./.github/workflows/torch.yml
    with:
      tag: ${{ format('nccl-cuda{0}-nccl{1}-torch{2}-vision{3}', matrix.image.cuda, matrix.image.nccl, matrix.torch, matrix.vision) }}
      builder-base-image: ghcr.io/coreweave/nccl-tests:${{ matrix.image.cuda }}-cudnn8-devel-ubuntu20.04-nccl${{ matrix.image.nccl }}-${{ matrix.image.nccl-tests-hash }}
      base-image: ghcr.io/coreweave/nccl-tests:${{ matrix.image.cuda }}-cudnn8-devel-ubuntu20.04-nccl${{ matrix.image.nccl }}-${{ matrix.image.nccl-tests-hash }}
      torch-version: ${{ matrix.torch }}
      torchvision-version: ${{ matrix.vision }}